### ISSUE TITLE
Algebraic effects

### ISSUE THREAD

**Issue by locriacyber** [giann/buzz#93]
With some changes, this language could support algebraic effects described in https://koka-lang.github.io/koka/doc/book.html.

1. add return type to exception
2. inside `catch`, allow `resume` to continue from where exception was triggered
3. new effect syntax

New syntax:
```
effect ReadValue<A> {
    fun read_one() > A 
}

fun willFail() > num !> ReadValue<num> {
    return read_one();
}

try {
    num result = needEffect();
    | result should be 42
} catch ReadValue<num>::read_one() {
    resume 42; | return value to effect
}
```

**Comment by giann** [comment]
Not sure I understand the example your provided. I don't really get the `effect` idea either.
What do you think this could bring to the table?

Reading from koka's doc, effects seem to be a strongly functional oriented language concept.
Buzz is not really a functional language even though you can use it as such.

I'd argue also that what you propose is syntactic sugar short of a feature which is coming to Buzz (object and protocol generics):
```buzz
protocol ReadValue<A> {
    fun readOne() > A;
}

fun willFail() > num !> ReadValue<num> {
    return readOne(); | Here I don't get your example: are you calling the ReadValue's method?
}

try {
    num result = needEffect();
} catch (ReadValue<num> effect) {
    | not sure what you wanted to do here, `resume` is the keyword to continue a yielded fiber
}
```

**Comment by locriacyber** [comment]
Languages like smalltalk allow the program to continue from where the exception was thrown.

Algebraic effects allow you to do the same thing, but type checked. For example, it allows you to expose system API as an effect, then type check the program (make sure it only uses certain API).

**Comment by giann** [comment]
> Languages like smalltalk allow the program to continue from where the exception was thrown.

Interesting idea.

I'm not planning on adding any new features of that caliber though. Buzz should remain relatively simple.
